name       = "cairo-fortran"
description= "Fortran bindings for the vector graphics Cairo library"
version    = "1.0.0"
license    = "GPL-3.0-or-later WITH GCC-exception-3.1"
author     = "The gtk-fortran team, including Brocolis"
copyright  = "2021-2023 The gtk-fortran team, including Brocolis"
maintainer = "https://github.com/vmagnin/cairo-fortran/issues"
homepage   = "https://github.com/vmagnin/cairo-fortran"
categories = ["bindings", "graphics"]
keywords   = ["cairo-fortran", "Cairo", "Fortran", "fpm", "vector graphics"]

[build]
link = "cairo"
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
